
const l2dData = [
  { 'group': '777', 'name': 'Blanc', 'id': 'c270' },
  { 'group': '777', 'name': 'Blanc White Rabbit', 'id': 'c270_01' },
  { 'group': '777', 'name': 'Blanc No.77 Batter', 'id': 'c270_02' },
  { 'group': '777', 'name': 'Blanc Fortune Express', 'id': 'c270_03' },
  { 'group': '777', 'name': 'Noir', 'id': 'c271' },
  { 'group': '777', 'name': 'Noir Black Rabbit', 'id': 'c271_01' },
  { 'group': '777', 'name': 'Noir Baseball Cheerleader', 'id': 'c271_02' },
  { 'group': '777', 'name': 'Rouge', 'id': 'c272' },
  { 'group': '777', 'name': 'Rouge Unlucky Rabbit', 'id': 'c272_01' },

  { 'group': 'A.C.P.U.', 'name': 'Poli', 'id': 'c030' },
  { 'group': 'A.C.P.U.', 'name': 'Poli Sweet Holic', 'id': 'c030_01' },
  { 'group': 'A.C.P.U.', 'name': 'Poli Cheer Up Police', 'id': 'c030_02' },
  { 'group': 'A.C.P.U.', 'name': 'Miranda', 'id': 'c032' },
  { 'group': 'A.C.P.U.', 'name': 'Miranda Thief of Justice', 'id': 'c032_01' },
  { 'group': 'A.C.P.U.', 'name': 'Quiry', 'id': 'c033' },
  { 'group': 'A.C.P.U.', 'name': 'Poli@Favorite', 'id': 'favorite_c030' },
  { 'group': 'A.C.P.U.', 'name': 'Miranda@Favorite', 'id': 'favorite_c032' },

  { 'group': 'Absolute', 'name': 'Emma', 'id': 'c090' },
  { 'group': 'Absolute', 'name': 'Emma Color Me Red', 'id': 'c090_01' },
  { 'group': 'Absolute', 'name': 'Emma Office Therapy', 'id': 'c090_02' },
  { 'group': 'Absolute', 'name': 'Vesti', 'id': 'c091' },
  { 'group': 'Absolute', 'name': 'Vesti Ark Mage', 'id': 'c091_01' },
  { 'group': 'Absolute', 'name': 'Eunhwa', 'id': 'c092' },
  { 'group': 'Absolute', 'name': 'Emma: Tactical Upgrade', 'id': 'c093' },
  { 'group': 'Absolute', 'name': 'Emma: Tactical Upgrade Secret Therapy', 'id': 'c093_01' },
  { 'group': 'Absolute', 'name': 'Vesti: Tactical Upgrade', 'id': 'c094' },
  { 'group': 'Absolute', 'name': 'Vesti: Tactical Upgrade Pure Beginner', 'id': 'c094_01' },
  { 'group': 'Absolute', 'name': 'Eunhwa: Tactical Upgrade', 'id': 'c095' },
  { 'group': 'Absolute', 'name': 'Eunhwa: Tactical Upgrade Day Off', 'id': 'c095_01' },

  { 'group': 'Aegis', 'name': 'Mast', 'id': 'c350' },
  { 'group': 'Aegis', 'name': 'Mast A Pirate\'s Heart', 'id': 'c350_01' },
  { 'group': 'Aegis', 'name': 'Mast the Driver', 'id': 'c350_02' },
  { 'group': 'Aegis', 'name': 'Mast: Outdated', 'id': 'c350_old' },
  { 'group': 'Aegis', 'name': 'Anchor', 'id': 'c351' },
  { 'group': 'Aegis', 'name': 'Anchor the Diver', 'id': 'c351_01' },
  { 'group': 'Aegis', 'name': 'Helm', 'id': 'c352' },
  { 'group': 'Aegis', 'name': 'Helm Chandelier', 'id': 'c352_01' },
  { 'group': 'Aegis', 'name': 'Helm Post-Shower Moment', 'id': 'c352_02' },
  { 'group': 'Aegis', 'name': 'Helm: Aquamarine', 'id': 'c353' },
  { 'group': 'Aegis', 'name': 'Mast: Romantic Maid', 'id': 'c354' },
  { 'group': 'Aegis', 'name': 'Mast: Romantic Maid Tea Service', 'id': 'c354_01' },
  { 'group': 'Aegis', 'name': 'Anchor: Innocent Maid', 'id': 'c355' },
  { 'group': 'Aegis', 'name': 'Helm@Favorite', 'id': 'favorite_c352' },

  { 'group': 'Best Seller', 'name': 'Phantom', 'id': 'c580' },
  { 'group': 'Best Seller', 'name': 'Arcana', 'id': 'c581' },
  { 'group': 'Best Seller', 'name': 'Label', 'id': 'c582' },
  { 'group': 'Best Seller', 'name': 'Arcana: Fortune Mate', 'id': 'c583' },

  { 'group': 'Botanic Garden', 'name': 'Flora', 'id': 'c411' },
  { 'group': 'Botanic Garden', 'name': 'Trina', 'id': 'c412' },
  { 'group': 'Botanic Garden', 'name': 'Trina Natural White', 'id': 'c412_01' },

  { 'group': 'Cafe Sweety', 'name': 'Sugar', 'id': 'c140' },
  { 'group': 'Cafe Sweety', 'name': 'Sugar Hard-Boiled', 'id': 'c140_01' },
  { 'group': 'Cafe Sweety', 'name': 'Sugar Wild Backyard', 'id': 'c140_02' },
  { 'group': 'Cafe Sweety', 'name': 'Milk', 'id': 'c141' },
  { 'group': 'Cafe Sweety', 'name': 'Milk Extreme Fighter', 'id': 'c141_01' },
  { 'group': 'Cafe Sweety', 'name': 'Frima', 'id': 'c142' },
  { 'group': 'Cafe Sweety', 'name': 'Frima Sea of Sloth', 'id': 'c142_01' },
  { 'group': 'Cafe Sweety', 'name': 'Milk Blooming Bunny', 'id': 'c143' },
  { 'group': 'Cafe Sweety', 'name': 'Milk@Favorite', 'id': 'favorite_c141' },
  { 'group': 'Cafe Sweety', 'name': 'Frima@Favorite', 'id': 'favorite_c142' },

  { 'group': 'Cooking Oil', 'name': 'Bready', 'id': 'c520' },
  { 'group': 'Cooking Oil', 'name': 'Bready Frosty Bite', 'id': 'c520_01' },
  { 'group': 'Cooking Oil', 'name': 'Crust', 'id': 'c521' },

  { 'group': 'Counters', 'name': 'Rapi', 'id': 'c010' },
  { 'group': 'Counters', 'name': 'Rapi: Outdated', 'id': 'c010_01' },
  { 'group': 'Counters', 'name': 'Rapi White Promise', 'id': 'c010_02' },
  { 'group': 'Counters', 'name': 'Rapi Classic Vacation', 'id': 'c010_03' },
  { 'group': 'Counters', 'name': 'Neon', 'id': 'c011' },
  { 'group': 'Counters', 'name': 'Neon Bling Bullet', 'id': 'c011_01' },
  { 'group': 'Counters', 'name': 'Anis', 'id': 'c012' },  
  { 'group': 'Counters', 'name': 'Neon: Blue Ocean', 'id': 'c014' },
  { 'group': 'Counters', 'name': 'Anis: Sparkling Summer', 'id': 'c015' },
  { 'group': 'Counters', 'name': 'Rapi: Red Hood', 'id': 'c016' },
  { 'group': 'Counters', 'name': 'Rapi: Red Hood Red Flavor', 'id': 'c016_01' },
  { 'group': 'Counters', 'name': 'Rapi: Red Hood Cherished Red', 'id': 'c016_02' },
  { 'group': 'Counters', 'name': 'Rapi: Red Hood Shining Light', 'id': 'c016_03' },
  { 'group': 'Counters', 'name': 'Anis: Star', 'id': 'c017' },
  { 'group': 'Counters', 'name': 'Anis: Starlight', 'id': 'c017_01' },
  { 'group': 'Counters', 'name': 'Anis: Star T.T.STAR', 'id': 'c017_02' },
  { 'group': 'Counters', 'name': 'Neon: Vision Eye', 'id': 'c018' },
  { 'group': 'Counters', 'name': 'Rapi: Red', 'id': 'c989' },
  { 'group': 'Counters', 'name': 'Rapi: Minor', 'id': 'c990' },
  { 'group': 'Counters', 'name': 'Rapi: Child', 'id': 'c992' },
  { 'group': 'Counters', 'name': 'Rapi: Origin', 'id': 'c994' },
  { 'group': 'Counters', 'name': 'Neon: Child', 'id': 'c9019' },

  { 'group': 'Dazzling Pear', 'name': 'Naga', 'id': 'c450' },
  { 'group': 'Dazzling Pear', 'name': 'Naga Elegant Date', 'id': 'c450_01' },
  { 'group': 'Dazzling Pear', 'name': 'Naga Last Girlhood', 'id': 'c450_02' },
  { 'group': 'Dazzling Pear', 'name': 'Tia', 'id': 'c451' },
  { 'group': 'Dazzling Pear', 'name': 'Tia Lovely Date', 'id': 'c451_01' },
  { 'group': 'Dazzling Pear', 'name': 'Tia Sweet Chef', 'id': 'c451_02' },

  { 'group': 'Electric Shock', 'name': 'Elegg', 'id': 'c500' },
  { 'group': 'Electric Shock', 'name': 'Trony', 'id': 'c501' },
  { 'group': 'Electric Shock', 'name': 'Trony Sweet Step', 'id': 'c501_01' },
  { 'group': 'Electric Shock', 'name': 'Elegg: Boom and Shock', 'id': 'c502' },

  { 'group': 'Exotic', 'name': 'Crow', 'id': 'c110' },
  { 'group': 'Exotic', 'name': 'Jackal', 'id': 'c111' },
  { 'group': 'Exotic', 'name': 'Jackal Class Troublemaker', 'id': 'c111_01' },
  { 'group': 'Exotic', 'name': 'Viper', 'id': 'c112' },
  { 'group': 'Exotic', 'name': 'Viper Toxic Rabbit', 'id': 'c112_01' },
  { 'group': 'Exotic', 'name': 'Viper Shine of Love', 'id': 'c112_02' },
  { 'group': 'Exotic', 'name': 'Viper Punky Street', 'id': 'c112_03' },
  { 'group': 'Exotic', 'name': 'E.H.', 'id': 'c113' },
  { 'group': 'Exotic', 'name': 'E.H.: Origin', 'id': 'c940' },
  { 'group': 'Exotic', 'name': 'Viper@Favorite', 'id': 'favorite_c112' },

  { 'group': 'Extrinsic', 'name': 'Guillotine', 'id': 'c180' },
  { 'group': 'Extrinsic', 'name': 'Guillotine Dark Tracer', 'id': 'c180_01' },
  { 'group': 'Extrinsic', 'name': 'Maiden', 'id': 'c181' },
  { 'group': 'Extrinsic', 'name': 'Maiden Covert Nurse', 'id': 'c181_01' },
  { 'group': 'Extrinsic', 'name': 'Maiden Under the Sun', 'id': 'c181_02' },
  { 'group': 'Extrinsic', 'name': 'Guillotine Winter Slayer', 'id': 'c182' },
  { 'group': 'Extrinsic', 'name': 'Maiden Ice Rose', 'id': 'c183' },

  { 'group': 'Four Beasts', 'name': 'Behemoth', 'id': 'c560' },
  { 'group': 'Four Beasts', 'name': 'Ziz', 'id': 'c561' },
  { 'group': 'Four Beasts', 'name': 'Leviathan', 'id': 'c562' },
  { 'group': 'Four Beasts', 'name': 'Bahamut', 'id': 'c563' },
  { 'group': 'Four Beasts', 'name': 'Leviathan: Origin', 'id': 'c996' },

  { 'group': 'Goddess', 'name': 'Snow White: Innocent Days', 'id': 'c224' },
  { 'group': 'Goddess', 'name': 'Scarlet: Black Shadow', 'id': 'c225' },
  { 'group': 'Goddess', 'name': 'Scarlet: Black Shadow Longing Flower', 'id': 'c225_01' },
  { 'group': 'Goddess', 'name': 'Rapunzel: Pure Grace', 'id': 'c226' },
  { 'group': 'Goddess', 'name': 'Dorothy', 'id': 'c233' },
  { 'group': 'Goddess', 'name': 'Dorothy Nostalgia', 'id': 'c233_01' },
  { 'group': 'Goddess', 'name': 'Dorothy Luna Light', 'id': 'c233_02' },
  { 'group': 'Goddess', 'name': 'Dorothy (CN)', 'id': 'c233_80' },
  { 'group': 'Goddess', 'name': 'Dorothy: Serendipity', 'id': 'c234' },
  { 'group': 'Goddess', 'name': 'Red Hood', 'id': 'c470' },
  { 'group': 'Goddess', 'name': 'Red Hood Nonsense Red', 'id': 'c470_01' },
  { 'group': 'Goddess', 'name': 'Red Hood Retro Days', 'id': 'c470_02' },
  { 'group': 'Goddess', 'name': 'Liliweiss', 'id': 'c943' },
  { 'group': 'Goddess', 'name': 'Rapunzel: Pure', 'id': 'c966' },

  { 'group': 'Hammer & Drill', 'name': 'Hammering', 'id': 'c490' },
  { 'group': 'Hammer & Drill', 'name': 'Drilley', 'id': 'c491' },

  { 'group': 'Happy Zoo', 'name': 'Nero', 'id': 'c380' },
  { 'group': 'Happy Zoo', 'name': 'Biscuit', 'id': 'c381' },
  { 'group': 'Happy Zoo', 'name': 'Biscuit Spring Puppy', 'id': 'c381_01' },
  { 'group': 'Happy Zoo', 'name': 'Leona', 'id': 'c382' },
  { 'group': 'Happy Zoo', 'name': 'Leona Zoo Keeper', 'id': 'c382_01' },

  { 'group': 'Heavy Gram', 'name': 'T.A.L.O.S', 'id': 'c361' },
  { 'group': 'Heavy Gram', 'name': 'Kilo', 'id': 'c977' },

  { 'group': 'Incubator', 'name': 'Mori', 'id': 'c590' },

  { 'group': 'Infinity Rail', 'name': 'Brid', 'id': 'c070' },
  { 'group': 'Infinity Rail', 'name': 'Brid Model Worker', 'id': 'c070_01' },
  { 'group': 'Infinity Rail', 'name': 'Brid Black Moon', 'id': 'c070_02' },
  { 'group': 'Infinity Rail', 'name': 'Soline', 'id': 'c071' },
  { 'group': 'Infinity Rail', 'name': 'Diesel', 'id': 'c072' },
  { 'group': 'Infinity Rail', 'name': 'Diesel Black Sunday', 'id': 'c072_01' },
  { 'group': 'Infinity Rail', 'name': 'Diesel Strawberry Flower', 'id': 'c072_02' },
  { 'group': 'Infinity Rail', 'name': 'Diesel Midnight Strawberry', 'id': 'c072_04' },
  { 'group': 'Infinity Rail', 'name': 'Brid: Silent Track', 'id': 'c073' },
  { 'group': 'Infinity Rail', 'name': 'Soline: Frost Ticket', 'id': 'c074' },
  { 'group': 'Infinity Rail', 'name': 'Diesel: Winter Sweets', 'id': 'c075' },
  { 'group': 'Infinity Rail', 'name': 'Diesel@Favorite', 'id': 'favorite_c072' },

  { 'group': 'Inherit', 'name': 'Harran', 'id': 'c230' },
  { 'group': 'Inherit', 'name': 'Harran Banquet Witch', 'id': 'c230_01' },
  { 'group': 'Inherit', 'name': 'Isabel', 'id': 'c231' },
  { 'group': 'Inherit', 'name': 'Isabel Honeymoon Party', 'id': 'c231_01' },
  { 'group': 'Inherit', 'name': 'Noah', 'id': 'c232' },
  
  { 'group': 'Liaozhai', 'name': 'Ying Ning', 'id': 'c8004' },  
  { 'group': 'Liaozhai', 'name': 'Hua Pi', 'id': 'c8005' },  
  { 'group': 'Liaozhai', 'name': 'Ying Ning Fox', 'id': 'c8006' },

  { 'group': 'M.M.R.', 'name': 'Mana', 'id': 'c290' },
  { 'group': 'M.M.R.', 'name': 'Ether', 'id': 'c291' },
  { 'group': 'M.M.R.', 'name': 'Marciana', 'id': 'c321' },
  { 'group': 'M.M.R.', 'name': 'Marciana School Days', 'id': 'c321_01' },

  { 'group': 'Maid For You', 'name': 'Ade', 'id': 'c310' },
  { 'group': 'Maid For You', 'name': 'Ade Maid in Spring', 'id': 'c310_01' },
  { 'group': 'Maid For You', 'name': 'Cocoa', 'id': 'c311' },
  { 'group': 'Maid For You', 'name': 'Soda', 'id': 'c312' },
  { 'group': 'Maid For You', 'name': 'Privaty: Unkind Maid', 'id': 'c313' },
  { 'group': 'Maid For You', 'name': 'Soda: Twinkling Bunny', 'id': 'c314' },
  { 'group': 'Maid For You', 'name': 'Ade: Agent Bunny', 'id': 'c315' },
  { 'group': 'Maid For You', 'name': 'Velvet', 'id': 'c316' },
  { 'group': 'Maid For You', 'name': 'Velvet: Sensual Rabbit', 'id': 'c316_01' },

  { 'group': 'Master Hand', 'name': 'Julia', 'id': 'c150' },
  { 'group': 'Master Hand', 'name': 'Julia Mild Nocturne', 'id': 'c150_01' },
  { 'group': 'Master Hand', 'name': 'Julia Summer Romance', 'id': 'c150_02' },
  { 'group': 'Master Hand', 'name': 'Julia@Favorite', 'id': 'favorite_c150' },

  { 'group': 'Matis', 'name': 'Laplace', 'id': 'c100' },
  { 'group': 'Matis', 'name': 'Drake', 'id': 'c101' },
  { 'group': 'Matis', 'name': 'Drake Villain Racer', 'id': 'c101_01' },
  { 'group': 'Matis', 'name': 'Drake Maid For Vilian', 'id': 'c101_02' },
  { 'group': 'Matis', 'name': 'Maxwell', 'id': 'c102' },
  { 'group': 'Matis', 'name': 'Maxwell Mechanic White', 'id': 'c102_01' },
  { 'group': 'Matis', 'name': 'Laplace: Upgrade', 'id': 'c103' },
  { 'group': 'Matis', 'name': 'Drake: Upgrade', 'id': 'c104' },
  { 'group': 'Matis', 'name': 'Maxwell: Upgrade', 'id': 'c105' },
  { 'group': 'Matis', 'name': 'Laplace@Favorite', 'id': 'favorite_c100' },
  { 'group': 'Matis', 'name': 'Drake@Favorite', 'id': 'favorite_c101' },

  { 'group': 'Mighty Tools', 'name': 'Centi', 'id': 'c080' },
  { 'group': 'Mighty Tools', 'name': 'Centi Supreme Holiday', 'id': 'c080_01' },
  { 'group': 'Mighty Tools', 'name': 'Centi Ocean Repair', 'id': 'c080_02' },
  { 'group': 'Mighty Tools', 'name': 'Liter', 'id': 'c082' },
  { 'group': 'Mighty Tools', 'name': 'Liter Guardfish', 'id': 'c082_01' },
  { 'group': 'Mighty Tools', 'name': 'Liter Cute Sunflower', 'id': 'c082_02' },
  { 'group': 'Mighty Tools', 'name': 'Liter (CN)', 'id': 'c082_80' },

  { 'group': 'Nepenthe', 'name': 'Rumani', 'id': 'c240' },
  { 'group': 'Nepenthe', 'name': 'Epinel', 'id': 'c241' },
  { 'group': 'Nepenthe', 'name': 'Folkwang', 'id': 'c242' },
  { 'group': 'Nepenthe', 'name': 'Folkwang Moist Bunny', 'id': 'c242_01' },

  { 'group': 'Old Tales', 'name': 'Grave', 'id': 'c510' },
  { 'group': 'Old Tales', 'name': 'Anachiro | Cinderella', 'id': 'c511' },
  { 'group': 'Old Tales', 'name': 'Anachiro | Cinderella Glass Princess', 'id': 'c511_01' },
  { 'group': 'Old Tales', 'name': 'Anachiro | Cinderella Beautiful Me', 'id': 'c511_02' },
  { 'group': 'Old Tales', 'name': 'Little Mermaid | Siren', 'id': 'c513' },
  { 'group': 'Old Tales', 'name': 'Little Mermaid | Siren Abyss Flower', 'id': 'c513_01' },
  { 'group': 'Old Tales', 'name': 'Little Mermaid | Siren Beautiful Bubble', 'id': 'c513_02' },
  { 'group': 'Old Tales', 'name': 'Grave the Great', 'id': 'c514' },
  { 'group': 'Old Tales', 'name': 'Grave the Great Beautiful You', 'id': 'c514_01' },
  { 'group': 'Old Tales', 'name': 'Anachiro', 'id': 'c944' },
  { 'group': 'Old Tales', 'name': 'Grave: Abe', 'id': 'c979' },
  { 'group': 'Old Tales', 'name': 'Hansel', 'id': 'c980' },
  { 'group': 'Old Tales', 'name': 'Gretel', 'id': 'c981' },
  { 'group': 'Old Tales', 'name': 'Red Shoes', 'id': 'c982' },

  { 'group': 'Over the Horizon', 'name': 'Sky', 'id': 'c530' },
  { 'group': 'Over the Horizon', 'name': 'Cielo', 'id': 'c531' },
  { 'group': 'Over the Horizon', 'name': 'Sora', 'id': 'c532' },
  { 'group': 'Over the Horizon', 'name': 'Sora Spring Flight', 'id': 'c532_01' },

  { 'group': 'Overseer', 'name': 'Eyeri', 'id': 'c440' },
  { 'group': 'Overseer', 'name': 'Avista', 'id': 'c441' },

  { 'group': 'Pathfinder', 'name': 'Liveryn', 'id': 'c480' },
  { 'group': 'Pathfinder', 'name': 'Fragile', 'id': 'c481' },

  { 'group': 'Perilous Siege', 'name': 'D', 'id': 'c040' },
  { 'group': 'Perilous Siege', 'name': 'K', 'id': 'c041' },
  { 'group': 'Perilous Siege', 'name': 'K: Undercover', 'id': 'c041_01' },
  { 'group': 'Perilous Siege', 'name': 'D: Killer Wife', 'id': 'c043' },
  { 'group': 'Perilous Siege', 'name': 'D: Killer Wife Secret Party Cleaner', 'id': 'c043_01' },
  { 'group': 'Perilous Siege', 'name': 'D: Killer Wife Secret Police', 'id': 'c043_02' },

  { 'group': 'Pioneer', 'name': 'Snow White', 'id': 'c220' },
  { 'group': 'Pioneer', 'name': 'Snow White White Knight', 'id': 'c220_01' },
  { 'group': 'Pioneer', 'name': 'Rapunzel', 'id': 'c221' },
  { 'group': 'Pioneer', 'name': 'Scarlet', 'id': 'c222' },
  { 'group': 'Pioneer', 'name': 'Scarlet: Racer\'s High', 'id': 'c222_01' },
  { 'group': 'Pioneer', 'name': 'Nayuta', 'id': 'c223' },
  { 'group': 'Pioneer', 'name': 'Nayuta: Wu Wei', 'id': 'c223_01' },
  { 'group': 'Pioneer', 'name': 'Pinocchio', 'id': 'c227' },
  { 'group': 'Pioneer', 'name': 'Snow White: Heavy Arms', 'id': 'c471' },
  { 'group': 'Pioneer', 'name': 'Nayuta Clone', 'id': 'c9008' },

  { 'group': 'Prima Donna', 'name': 'Noise', 'id': 'c430' },
  { 'group': 'Prima Donna', 'name': 'Noise Cherry Blossom Stage', 'id': 'c430_01' },
  { 'group': 'Prima Donna', 'name': 'Noise Classic Diva', 'id': 'c430_02' },
  { 'group': 'Prima Donna', 'name': 'Volume', 'id': 'c431' },
  { 'group': 'Prima Donna', 'name': 'Volume Beat the Gun', 'id': 'c431_01' },
  { 'group': 'Prima Donna', 'name': 'Aria', 'id': 'c432' },

  { 'group': 'Protocol', 'name': 'Exia', 'id': 'c210' },
  { 'group': 'Protocol', 'name': 'Exia Joy to the Nerds', 'id': 'c210_01' },
  { 'group': 'Protocol', 'name': 'Exia Gamer', 'id': 'c210_02' },
  { 'group': 'Protocol', 'name': 'Exia Hacker Rabbit', 'id': 'c210_03' },
  { 'group': 'Protocol', 'name': 'Novel', 'id': 'c212' },
  { 'group': 'Protocol', 'name': 'Novel Penguin Holmes', 'id': 'c212_01' },
  { 'group': 'Protocol', 'name': 'Novel Detective Nurse', 'id': 'c212_02' },
  { 'group': 'Protocol', 'name': 'Exia@Favorite', 'id': 'favorite_c210' },

  { 'group': 'Real Kindness', 'name': 'Guilty', 'id': 'c400' },
  { 'group': 'Real Kindness', 'name': 'Guilty Wave of Disbelief', 'id': 'c400_01' },
  { 'group': 'Real Kindness', 'name': 'Sin', 'id': 'c401' },
  { 'group': 'Real Kindness', 'name': 'Sin Backstreet Dream', 'id': 'c401_01' },
  { 'group': 'Real Kindness', 'name': 'Quency', 'id': 'c402' },
  { 'group': 'Real Kindness', 'name': 'Quency Escape Queen', 'id': 'c403' },
  { 'group': 'Real Kindness', 'name': 'Quency Escape Queen Masquerade Swan', 'id': 'c403_01' },

  { 'group': 'Recall & Release', 'name': 'N102', 'id': 'c120' },
  { 'group': 'Recall & Release', 'name': 'Anne: Miracle Fairy', 'id': 'c121' },

  { 'group': 'Rewind', 'name': 'Bay', 'id': 'c550' },
  { 'group': 'Rewind', 'name': 'Bay Radiant Rabbit', 'id': 'c550_01' },
  { 'group': 'Rewind', 'name': 'Clay', 'id': 'c551' },
  { 'group': 'Rewind', 'name': 'Clay Cheer Up Training', 'id': 'c551_01' },
  { 'group': 'Rewind', 'name': 'Bay@Favorite', 'id': 'favorite_c550' },

  { 'group': 'School Circle', 'name': 'Zwei', 'id': 'c390' },
  { 'group': 'School Circle', 'name': 'Zwei First Festa', 'id': 'c390_01' },
  { 'group': 'School Circle', 'name': 'Zwei Spring Stroll', 'id': 'c390_02' },
  { 'group': 'School Circle', 'name': 'Ein', 'id': 'c391' },
  { 'group': 'School Circle', 'name': 'Ein Handmade Festa', 'id': 'c391_01' },
  { 'group': 'School Circle', 'name': 'Rei', 'id': 'c392' },

  { 'group': 'Seraphim', 'name': 'Mary', 'id': 'c130' },
  { 'group': 'Seraphim', 'name': 'Mary Medical Rabbit', 'id': 'c130_01' },
  { 'group': 'Seraphim', 'name': 'Pepper', 'id': 'c131' },
  { 'group': 'Seraphim', 'name': 'Pepper Ocean Vitamin', 'id': 'c131_01' },
  { 'group': 'Seraphim', 'name': 'Mary: Bay Goddess', 'id': 'c132' },
  
  { 'group': 'Shade', 'name': 'Velvet', 'id': 'c9004' },

  { 'group': 'T.T. STAR', 'name': 'Mint: Star', 'id': 'c600' },
  { 'group': 'T.T. STAR', 'name': 'Mint', 'id': 'c600_01' },
  { 'group': 'T.T. STAR', 'name': 'Mint: Training', 'id': 'c600_02' },
  { 'group': 'T.T. STAR', 'name': 'Prika', 'id': 'c601' },
  { 'group': 'T.T. STAR', 'name': 'Prika: Star', 'id': 'c601_01' },
  { 'group': 'T.T. STAR', 'name': 'Prika: Training', 'id': 'c601_02' },
  { 'group': 'T.T. STAR', 'name': 'Anis', 'id': 'c9021' },
  { 'group': 'T.T. STAR', 'name': 'Anis: Training', 'id': 'c9021_01' },

  { 'group': 'Talentum', 'name': 'Rupee', 'id': 'c200' },
  { 'group': 'Talentum', 'name': 'Rupee Rabbit Deluxe', 'id': 'c200_01' },
  { 'group': 'Talentum', 'name': 'Yan', 'id': 'c201' },
  { 'group': 'Talentum', 'name': 'Yan Sunrise Market', 'id': 'c201_01' },
  { 'group': 'Talentum', 'name': 'Dolla', 'id': 'c202' },
  { 'group': 'Talentum', 'name': 'Dolla Dark Rose', 'id': 'c202_01' },
  { 'group': 'Talentum', 'name': 'Rupee: Winter Shopper', 'id': 'c203' },

  { 'group': 'The Carronades', 'name': 'Belorta', 'id': 'c060' },
  { 'group': 'The Carronades', 'name': 'Mica', 'id': 'c061' },
  { 'group': 'The Carronades', 'name': 'Mica: Snow Buddy', 'id': 'c062' },

  { 'group': 'The Scouts', 'name': 'Delta', 'id': 'c020' },
  { 'group': 'The Scouts', 'name': 'Signal', 'id': 'c022' },
  { 'group': 'The Scouts', 'name': 'Signal Dramatic Chocolate', 'id': 'c022_01' },
  { 'group': 'The Scouts', 'name': 'Delta: Ninja Thief', 'id': 'c023' },

  { 'group': 'Triangle', 'name': 'Privaty', 'id': 'c170' },
  { 'group': 'Triangle', 'name': 'Privaty Government Grunt', 'id': 'c170_01' },
  { 'group': 'Triangle', 'name': 'Privaty Banquet Princess', 'id': 'c170_02' },
  { 'group': 'Triangle', 'name': 'Privaty Destined in Blue', 'id': 'c170_03' },
  { 'group': 'Triangle', 'name': 'Privaty Sharp Lesson', 'id': 'c170_04' },
  { 'group': 'Triangle', 'name': 'Yulha', 'id': 'c171' },
  { 'group': 'Triangle', 'name': 'Admi', 'id': 'c172' },

  { 'group': 'Underworld Queen', 'name': 'Rosanna', 'id': 'c280' },
  { 'group': 'Underworld Queen', 'name': 'Rosanna Ms. Dangerous', 'id': 'c280_01' },
  { 'group': 'Underworld Queen', 'name': 'Moran', 'id': 'c281' },
  { 'group': 'Underworld Queen', 'name': 'Moran Off-Duty Queen', 'id': 'c281_01' },
  { 'group': 'Underworld Queen', 'name': 'Sakura', 'id': 'c282' },
  { 'group': 'Underworld Queen', 'name': 'Sakura Midnight Stealth', 'id': 'c282_01' },
  { 'group': 'Underworld Queen', 'name': 'Rosanna: Chic Oceon', 'id': 'c283' },
  { 'group': 'Underworld Queen', 'name': 'Sakura: Bloom in Summer', 'id': 'c284' },

  { 'group': 'Unlimited', 'name': 'Ludmilla', 'id': 'c190' },
  { 'group': 'Unlimited', 'name': 'Alice', 'id': 'c191' },
  { 'group': 'Unlimited', 'name': 'Alice Sweet Home', 'id': 'c191_01' },
  { 'group': 'Unlimited', 'name': 'Alice Märchen Dream', 'id': 'c191_02' },
  { 'group': 'Unlimited', 'name': 'Tove', 'id': 'c192' },
  { 'group': 'Unlimited', 'name': 'Tove Baseball Fan', 'id': 'c192_01' },
  { 'group': 'Unlimited', 'name': 'Tove Sunblaze', 'id': 'c192_02' },
  { 'group': 'Unlimited', 'name': 'Neve', 'id': 'c193' },
  { 'group': 'Unlimited', 'name': 'Ludmilla: Winter Owner', 'id': 'c194' },
  { 'group': 'Unlimited', 'name': 'Alice: Wonderland Bunny', 'id': 'c195' },
  { 'group': 'Unlimited', 'name': 'Tove@Favorite', 'id': 'favorite_c192' },

  { 'group': 'Veiled Order', 'name': 'Snow Crane', 'id': 'c620' },
  
  { 'group': 'Wardress', 'name': 'Yuni', 'id': 'c160' },
  { 'group': 'Wardress', 'name': 'Yuni Pretty In Pink', 'id': 'c160_01' },
  { 'group': 'Wardress', 'name': 'Mihara', 'id': 'c161' },
  { 'group': 'Wardress', 'name': 'Mihara: Upgrade', 'id': 'c162' },
  { 'group': 'Wardress', 'name': 'Mihara: Upgrade Paint Eater', 'id': 'c162_01' },
  { 'group': 'Wardress', 'name': 'Yuni: Upgrade', 'id': 'c985' },

  { 'group': 'White Knight', 'name': 'Crown', 'id': 'c330' },
  { 'group': 'White Knight', 'name': 'Crown Naked King', 'id': 'c330_01' },
  { 'group': 'White Knight', 'name': 'Crown Glorious Flower', 'id': 'c330_02' },
  { 'group': 'White Knight', 'name': 'Chime', 'id': 'c331' },

  { 'group': '_AI', 'name': 'Eternity', 'id': 'c370' },
  { 'group': '_AI', 'name': 'Endless', 'id': 'c371' },
  { 'group': '_AI', 'name': 'Einkk', 'id': 'c928' },
  { 'group': '_AI', 'name': 'Enikk', 'id': 'c904' },

  { 'group': '_Ark', 'name': 'Mekami Shifty', 'id': 'c610' },
  { 'group': '_Ark', 'name': 'Rian', 'id': 'c905' },
  { 'group': '_Ark', 'name': 'Shifty', 'id': 'c907' },
  { 'group': '_Ark', 'name': 'Shifty_old', 'id': 'c907_01' },
  { 'group': '_Ark', 'name': 'Papillon', 'id': 'c908' },
  { 'group': '_Ark', 'name': 'Jein', 'id': 'c973' },

  { 'group': '_CEO', 'name': 'Ingrid', 'id': 'c900' },
  { 'group': '_CEO', 'name': 'Syuen', 'id': 'c901' },
  { 'group': '_CEO', 'name': 'Mustang', 'id': 'c902' },
  { 'group': '_CEO', 'name': 'Mustang (CN)', 'id': 'c902_01' },
  { 'group': '_CEO', 'name': 'Mustang: Origin', 'id': 'c9022' },
  { 'group': '_CEO', 'name': 'Mustang: Hanson', 'id': 'c9023' },

  { 'group': '_Commander', 'name': 'Andersen', 'id': 'c903' },
  { 'group': '_Commander', 'name': 'Andersen Soaked', 'id': 'c903_01' },
  { 'group': '_Commander', 'name': 'Burningum', 'id': 'c914' },
  { 'group': '_Commander', 'name': 'Doban', 'id': 'c939' },
  { 'group': '_Commander', 'name': 'Commander (GODDESS)', 'id': 'c942' },
  { 'group': '_Commander', 'name': 'Oswald', 'id': 'c961' },
  { 'group': '_Commander', 'name': 'Oswald Casual', 'id': 'c961_01' },

  { 'group': '_Eden', 'name': 'Johan', 'id': 'c925' },
  { 'group': '_Eden', 'name': 'Cecil', 'id': 'c929' },

  { 'group': '_Heretic', 'name': 'Modernia: Marian', 'id': 'c013' },
  { 'group': '_Heretic', 'name': 'Modernia', 'id': 'c260' },
  { 'group': '_Heretic', 'name': 'Modernia First Affection', 'id': 'c260_01' },
  { 'group': '_Heretic', 'name': 'Modernia Second Affection', 'id': 'c260_02' },
  { 'group': '_Heretic', 'name': 'Modernia (CN)', 'id': 'c260_80' },
  { 'group': '_Heretic', 'name': 'Nihilister', 'id': 'c261' },
  { 'group': '_Heretic', 'name': 'Liberalio', 'id': 'c262' },
  { 'group': '_Heretic', 'name': 'Liberalio Dreaming Lake', 'id': 'c262_01' },
  { 'group': '_Heretic', 'name': 'Indivilia', 'id': 'c263' },
  { 'group': '_Heretic', 'name': 'Only One', 'id': 'c997' },
  { 'group': '_Heretic', 'name': 'Nihilister Hood', 'id': 'c9009' },
  { 'group': '_Heretic', 'name': 'Mass-Produced Heretic', 'id': 'c9014' },
  { 'group': '_Heretic', 'name': 'Altruia', 'id': 'c9017' },
  { 'group': '_Heretic', 'name': 'Egovista', 'id': 'c9025' },

  { 'group': '_Melee', 'name': 'Scarlet', 'id': 'c965' },
  { 'group': '_Melee', 'name': 'Rose', 'id': 'c971' },
  { 'group': '_Melee', 'name': 'Rose: Mirror', 'id': 'c971_01' },
  { 'group': '_Melee', 'name': 'zMelee', 'id': 'c974' },
  { 'group': '_Melee', 'name': 'zMelee 2', 'id': 'c974_01' },

  { 'group': '_Npc', 'name': 'Logey', 'id': 'c482' },
  { 'group': '_Npc', 'name': 'Black Ark Ranger', 'id': 'c570' },
  { 'group': '_Npc', 'name': 'Angelina', 'id': 'c934' },
  { 'group': '_Npc', 'name': 'Joseph', 'id': 'c935' },
  { 'group': '_Npc', 'name': 'Pinne', 'id': 'c941' },
  { 'group': '_Npc', 'name': 'Freesia: Child', 'id': 'c960' },
  { 'group': '_Npc', 'name': 'Lumi', 'id': 'c970' },
  { 'group': '_Npc', 'name': 'Nadia', 'id': 'c983' },
  { 'group': '_Npc', 'name': 'D.E.E.P', 'id': 'c991' },
  { 'group': '_Npc', 'name': 'Hermin', 'id': 'c998' },
  { 'group': '_Npc', 'name': 'Spirit Pinne', 'id': 'c9001' },
  { 'group': '_Npc', 'name': 'Nora', 'id': 'c9002' },
  { 'group': '_Npc', 'name': 'Mrs. Miss', 'id': 'c9003' },
  { 'group': '_Npc', 'name': 'Deipara', 'id': 'c9006' },
  { 'group': '_Npc', 'name': 'V.T.C. Priestess', 'id': 'c9016' },
  { 'group': '_Npc', 'name': 'Princess', 'id': 'c9018' },
  { 'group': '_Npc', 'name': 'Freesia: Star', 'id': 'c9020' },
  { 'group': '_Npc', 'name': 'Freesia', 'id': 'c9020_01' },
  { 'group': '_Npc', 'name': 'Yoyo', 'id': 'c9024' },
  { 'group': '_Npc', 'name': 'Amy', 'id': 'c9026' },

  { 'group': '_Other', 'name': 'Mass Produced: Red', 'id': 'c250' },
  { 'group': '_Other', 'name': 'Mass Produced: Blue', 'id': 'c251' },
  { 'group': '_Other', 'name': 'Mass Produced: Orange', 'id': 'c252' },
  { 'group': '_Other', 'name': 'Mass Produced: Green', 'id': 'c253' },
  { 'group': '_Other', 'name': 'Mass Produced: Purple', 'id': 'c254' },
  { 'group': '_Other', 'name': 'Mass Produced: White', 'id': 'c255' },
  { 'group': '_Other', 'name': 'Replace: Soldier EG', 'id': 'c300' },
  { 'group': '_Other', 'name': 'Replace: Soldier FA', 'id': 'c301' },
  { 'group': '_Other', 'name': 'Replace: Product 08', 'id': 'c302' },
  { 'group': '_Other', 'name': 'Replace: Product 12', 'id': 'c303' },
  { 'group': '_Other', 'name': 'Replace: iDoll Flower', 'id': 'c304' },
  { 'group': '_Other', 'name': 'Replace: iDoll Ocean', 'id': 'c305' },
  { 'group': '_Other', 'name': 'Replace: Soldier OW', 'id': 'c306' },
  { 'group': '_Other', 'name': 'Replace: Product 23', 'id': 'c307' },
  { 'group': '_Other', 'name': 'Replace: iDoll Sun', 'id': 'c308' },
  { 'group': '_Other', 'name': 'Hologram', 'id': 'c910' },
  { 'group': '_Other', 'name': 'Hologram: Sweet Johnny', 'id': 'c910_01' },
  { 'group': '_Other', 'name': 'Faceless Gentlemen', 'id': 'c911' },
  { 'group': '_Other', 'name': 'Faceless Lady', 'id': 'c912' },
  { 'group': '_Other', 'name': 'Robot: Raptillion', 'id': 'c915' },
  { 'group': '_Other', 'name': 'Faceless NPC 01', 'id': 'c916' },
  { 'group': '_Other', 'name': 'Faceless NPC 02', 'id': 'c917' },
  { 'group': '_Other', 'name': 'Faceless NPC 03', 'id': 'c918' },
  { 'group': '_Other', 'name': 'Faceless NPC 04', 'id': 'c919' },
  { 'group': '_Other', 'name': 'Faceless NPC 05', 'id': 'c920' },
  { 'group': '_Other', 'name': 'Faceless NPC 06', 'id': 'c921' },
  { 'group': '_Other', 'name': 'Faceless NPC 07', 'id': 'c922' },
  { 'group': '_Other', 'name': 'Faceless NPC 08', 'id': 'c923' },
  { 'group': '_Other', 'name': 'Faceless NPC 09', 'id': 'c924' },
  { 'group': '_Other', 'name': 'Animal: Beatrice', 'id': 'c930' },
  { 'group': '_Other', 'name': 'Robot: Roam', 'id': 'c931' },
  { 'group': '_Other', 'name': 'Robot: Com', 'id': 'c931_01' },
  { 'group': '_Other', 'name': 'Animal: Bolt Junior', 'id': 'c932' },
  { 'group': '_Other', 'name': 'Animal: Bolt', 'id': 'c933' },
  { 'group': '_Other', 'name': 'Animal: Max', 'id': 'c936' },
  { 'group': '_Other', 'name': 'Animal: Booboo', 'id': 'c937' },
  { 'group': '_Other', 'name': 'Robot: Katie', 'id': 'c945' },
  { 'group': '_Other', 'name': 'Animal: Ruru', 'id': 'c946' },
  { 'group': '_Other', 'name': 'Faceless NPC 10', 'id': 'c947' },
  { 'group': '_Other', 'name': 'Faceless NPC 11', 'id': 'c948' },
  { 'group': '_Other', 'name': 'Faceless NPC 12', 'id': 'c951' },
  { 'group': '_Other', 'name': 'Faceless NPC 13', 'id': 'c952' },
  { 'group': '_Other', 'name': 'Replace: Product 12 B-0006', 'id': 'c962' },
  { 'group': '_Other', 'name': 'Replace: Product 12 C-1002', 'id': 'c963' },
  { 'group': '_Other', 'name': 'Replace: Product 12 6000-D', 'id': 'c964' },
  { 'group': '_Other', 'name': 'Spirit: Lumi', 'id': 'c967' },
  { 'group': '_Other', 'name': 'Spirit: Lua', 'id': 'c968' },
  { 'group': '_Other', 'name': 'Spirit: Lena', 'id': 'c969' },
  { 'group': '_Other', 'name': 'Animal: Timi', 'id': 'c975' },
  { 'group': '_Other', 'name': 'Hologram: T.Rony', 'id': 'c976' },
  { 'group': '_Other', 'name': 'Faceless Chloe - Village Guardian', 'id': 'c988' },
  { 'group': '_Other', 'name': 'Robot: Mecha Shifty', 'id': 'c993' },
  { 'group': '_Other', 'name': 'Ghost Alfred', 'id': 'c9000' },
  { 'group': '_Other', 'name': 'Ghost Neaty', 'id': 'c9000_01' },
  { 'group': '_Other', 'name': 'Ghost Sizzly', 'id': 'c9000_02' },
  { 'group': '_Other', 'name': 'Ghost Fixy', 'id': 'c9000_03' },
  { 'group': '_Other', 'name': 'Ghost Detaily', 'id': 'c9000_05' },
  { 'group': '_Other', 'name': 'Ghost Sellsy', 'id': 'c9000_06' },
  { 'group': '_Other', 'name': 'Ghost', 'id': 'c9000_07' },
  { 'group': '_Other', 'name': 'Faceless NPC 14', 'id': 'c9015' },
  { 'group': '_Other', 'name': 'AZX: Soline 1', 'id': 'azxservicetime_1' },
  { 'group': '_Other', 'name': 'AZX: Soline 2', 'id': 'azxservicetime_2' },
  { 'group': '_Other', 'name': 'AZX: Diesel 1', 'id': 'azxservicetime_4' },
  { 'group': '_Other', 'name': 'AZX: Diesel 2', 'id': 'azxservicetime_5' },
  { 'group': '_Other', 'name': 'AZX: Brid 1', 'id': 'azxservicetime_7' },
  { 'group': '_Other', 'name': 'AZX: Brid 2', 'id': 'azxservicetime_8' },
  { 'group': '_Other', 'name': 'Smol: Anis', 'id': 'smol_anis' },
  { 'group': '_Other', 'name': 'Smol: Ade', 'id': 'smol_ade' },
  { 'group': '_Other', 'name': 'Smol: Anchor', 'id': 'smol_anchor' },
  { 'group': '_Other', 'name': 'Smol: Anchor Pirate', 'id': 'smol_anchor_pirate' },
  { 'group': '_Other', 'name': 'Smol: Bolt', 'id': 'smol_bolt' },
  { 'group': '_Other', 'name': 'Smol: Emilia', 'id': 'smol_emilia' },
  { 'group': '_Other', 'name': 'Smol: Frima', 'id': 'smol_frima' },
  { 'group': '_Other', 'name': 'Smol: Helm', 'id': 'smol_helm' },
  { 'group': '_Other', 'name': 'Smol: Liter', 'id': 'smol_liter' },
  { 'group': '_Other', 'name': 'Smol: Mary', 'id': 'smol_mary' },
  { 'group': '_Other', 'name': 'Smol: Mast', 'id': 'smol_mast' },
  { 'group': '_Other', 'name': 'Smol: Mast Pirate', 'id': 'smol_mast_pirate' },
  { 'group': '_Other', 'name': 'Smol: Maid Privaty', 'id': 'smol_mpriv' },
  { 'group': '_Other', 'name': 'Smol: Mint', 'id': 'smol_mint' },
  { 'group': '_Other', 'name': 'Smol: Pepper', 'id': 'smol_pepper' },
  { 'group': '_Other', 'name': 'Smol: Prika', 'id': 'smol_prika' },
  { 'group': '_Other', 'name': 'Smol: Ram', 'id': 'smol_ram' },
  { 'group': '_Other', 'name': 'Smol: Rapi', 'id': 'smol_rapi' },
  { 'group': '_Other', 'name': 'Smol: Rem', 'id': 'smol_rem' },
  { 'group': '_Other', 'name': 'Smol: Sin Pirate', 'id': 'smol_sin_pirate' },
  { 'group': '_Other', 'name': 'Smol: Yan', 'id': 'smol_yan' },  

  { 'group': '__Collab Airborne Squad', 'name': 'EVE', 'id': 'c850' },
  { 'group': '__Collab Airborne Squad', 'name': 'EVE Keyhole Dress', 'id': 'c850_01' },
  { 'group': '__Collab Airborne Squad', 'name': 'EVE Neurolink Suit', 'id': 'c850_02' },
  { 'group': '__Collab Airborne Squad', 'name': 'EVE Skin Suit', 'id': 'c850_03' },
  { 'group': '__Collab Airborne Squad', 'name': 'Raven Keyhole Dress', 'id': 'c851' },
  { 'group': '__Collab Airborne Squad', 'name': 'Raven Planet Diving Suit (6th) V2', 'id': 'c851_01' },
  { 'group': '__Collab Airborne Squad', 'name': 'Raven Midsummer Alice', 'id': 'c851_02' },
  { 'group': '__Collab Airborne Squad', 'name': 'Lily', 'id': 'c852' },
  { 'group': '__Collab Airborne Squad', 'name': 'Adam', 'id': 'c853' },

  { 'group': '__Collab B.S.T.', 'name': 'Ada', 'id': 'c840' },
  { 'group': '__Collab B.S.T.', 'name': 'Ada Seperate Ways', 'id': 'c840_01' },
  { 'group': '__Collab B.S.T.', 'name': 'Ada Dress', 'id': 'c840_02' },
  { 'group': '__Collab B.S.T.', 'name': 'Jill', 'id': 'c841' },
  { 'group': '__Collab B.S.T.', 'name': 'Jill Classic', 'id': 'c841_01' },
  { 'group': '__Collab B.S.T.', 'name': 'Jill Battle Suit', 'id': 'c841_02' },
  { 'group': '__Collab B.S.T.', 'name': 'Claire', 'id': 'c842' },

  { 'group': '__Collab Café LycoReco', 'name': 'Chisato', 'id': 'c860' },
  { 'group': '__Collab Café LycoReco', 'name': 'Chisato DA Training Wear (First)', 'id': 'c860_01' },
  { 'group': '__Collab Café LycoReco', 'name': 'Chisato Red Spark Guitar', 'id': 'c860_02' },
  { 'group': '__Collab Café LycoReco', 'name': 'Takina', 'id': 'c861' },
  { 'group': '__Collab Café LycoReco', 'name': 'Takina DA Training Wear (Second)', 'id': 'c861_01' },
  { 'group': '__Collab Café LycoReco', 'name': 'Takina Blue Pulse Bass', 'id': 'c861_02' },
  { 'group': '__Collab Café LycoReco', 'name': 'Kurumi', 'id': 'c862' },
  { 'group': '__Collab Café LycoReco', 'name': 'Jane', 'id': 'c9010' },
  { 'group': '__Collab Café LycoReco', 'name': 'Rain', 'id': 'c9011' },

  { 'group': '__Collab Devil Hunter', 'name': 'Makima', 'id': 'c800' },
  { 'group': '__Collab Devil Hunter', 'name': 'Makima Coat Off', 'id': 'c800_01' },
  { 'group': '__Collab Devil Hunter', 'name': 'Power', 'id': 'c801' },
  { 'group': '__Collab Devil Hunter', 'name': 'Himeno', 'id': 'c802' },
  { 'group': '__Collab Devil Hunter', 'name': 'Denji', 'id': 'c803' },
  { 'group': '__Collab Devil Hunter', 'name': 'Denji Chainsaw Man', 'id': 'c803_01' },
  { 'group': '__Collab Devil Hunter', 'name': 'Aki Hayakawa', 'id': 'c804' },

  { 'group': '__Collab Emilia\'s Faction', 'name': 'Rem', 'id': 'c820' },
  { 'group': '__Collab Emilia\'s Faction', 'name': 'Rem Handy Maid', 'id': 'c820_01' },
  { 'group': '__Collab Emilia\'s Faction', 'name': 'Rem Pure Blossom', 'id': 'c820_02' },
  { 'group': '__Collab Emilia\'s Faction', 'name': 'Emilia', 'id': 'c821' },
  { 'group': '__Collab Emilia\'s Faction', 'name': 'Emilia Clumsy Maid', 'id': 'c821_01' },
  { 'group': '__Collab Emilia\'s Faction', 'name': 'Emilia Spring Breeze', 'id': 'c821_02' },
  { 'group': '__Collab Emilia\'s Faction', 'name': 'Ram', 'id': 'c822' },

  { 'group': '__Collab NERV', 'name': 'Asuka Shikinami', 'id': 'c830' },
  { 'group': '__Collab NERV', 'name': 'Asuka Shikinami School Uniform', 'id': 'c830_01' },
  { 'group': '__Collab NERV', 'name': 'Asuka Shikinami Cynical Street', 'id': 'c830_02' },
  { 'group': '__Collab NERV', 'name': 'Asuka Shikinami Test Plugsuit', 'id': 'c830_03' },
  { 'group': '__Collab NERV', 'name': 'Rei Ayanami', 'id': 'c831' },
  { 'group': '__Collab NERV', 'name': 'Rei Ayanami School Uniform', 'id': 'c831_01' },
  { 'group': '__Collab NERV', 'name': 'Rei Ayanami Peaceful Vacation', 'id': 'c831_02' },
  { 'group': '__Collab NERV', 'name': 'Mari Makinami', 'id': 'c832' },
  { 'group': '__Collab NERV', 'name': 'Mari Makinami School Uniform', 'id': 'c832_01' },
  { 'group': '__Collab NERV', 'name': 'Mari Makinami Leisure Travel', 'id': 'c832_02' },
  { 'group': '__Collab NERV', 'name': 'Mari Makinami Final Battle', 'id': 'c832_03' },
  { 'group': '__Collab NERV', 'name': 'Mari Makinami Mystery Muse', 'id': 'c832_04' },
  { 'group': '__Collab NERV', 'name': 'Misato Katsuragi', 'id': 'c833' },

  { 'group': '__Collab WILLE', 'name': 'Rei Ayanami Tentative Name', 'id': 'c834' },
  { 'group': '__Collab WILLE', 'name': 'Rei Ayanami Miss Lookalike from Village-3', 'id': 'c834_01' },
  { 'group': '__Collab WILLE', 'name': 'Rei Ayanami Soul Connect', 'id': 'c834_02' },
  { 'group': '__Collab WILLE', 'name': 'Asuka Shikinami WILLE', 'id': 'c835' },
  { 'group': '__Collab WILLE', 'name': 'Asuka Shikinami Final Battle', 'id': 'c835_01' },
  { 'group': '__Collab WILLE', 'name': 'Asuka Shikinami Ocean\'s Lament', 'id': 'c835_02' },
  { 'group': '__Collab WILLE', 'name': 'Sakura Suzuhara', 'id': 'c836' },
  
  { 'group': '__Collab YoRHa', 'name': '2B', 'id': 'c810' },
  { 'group': '__Collab YoRHa', 'name': '2B Metamorphic Damage', 'id': 'c810_01' },
  { 'group': '__Collab YoRHa', 'name': '2B YoRHa Uniform 1', 'id': 'c810_02' },
  { 'group': '__Collab YoRHa', 'name': '2B Unofficial Waterfront Gear 1', 'id': 'c810_03' },
  { 'group': '__Collab YoRHa', 'name': 'A2', 'id': 'c811' },
  { 'group': '__Collab YoRHa', 'name': 'A2 Metamorphic Damage', 'id': 'c811_01' },
  { 'group': '__Collab YoRHa', 'name': 'A2 YoRHa Uniform Prototype', 'id': 'c811_02' },
  { 'group': '__Collab YoRHa', 'name': 'A2 Unofficial Waterfront Gear Prototype', 'id': 'c811_03' },
  { 'group': '__Collab YoRHa', 'name': 'Pascal', 'id': 'c812' },
  { 'group': '__Collab YoRHa', 'name': '9S', 'id': 'c813' },

  { 'group': '__Event', 'name': 'No Caller ID', 'id': 'nocallerid' },
  { 'group': '__Event', 'name': 'Hightech Toy', 'id': 'hightechtoy' },
  { 'group': '__Event', 'name': 'Miracle Snow', 'id': 'miraclesnow' },
  { 'group': '__Event', 'name': 'Brand New Year', 'id': 'brandnewyear' },
  { 'group': '__Event', 'name': 'D Outsider', 'id': 'doutsider' },
  { 'group': '__Event', 'name': 'Maid in Valentine', 'id': 'maidinvalentine' },
  { 'group': '__Event', 'name': 'Bow Wow Paradise', 'id': 'bowwowparadise' },
  { 'group': '__Event', 'name': 'Cherry Blossom', 'id': 'cherryblossom' },
  { 'group': '__Event', 'name': 'License to Kill', 'id': 'ltk' },
  { 'group': '__Event', 'name': 'White Memory 1', 'id': 'whitememory1' },
  { 'group': '__Event', 'name': 'White Memory 2', 'id': 'whitememory2' },
  { 'group': '__Event', 'name': 'Bunny x 777', 'id': '777' },
  { 'group': '__Event', 'name': 'Queen\'s Order', 'id': 'queensorder' },
  { 'group': '__Event', 'name': 'Blue Water Island', 'id': 'bluewaterisland' },
  { 'group': '__Event', 'name': 'Nya Nya Paradise', 'id': 'nyanyaparadise' },
  { 'group': '__Event', 'name': 'Golden Ship', 'id': 'goldenship' },
  { 'group': '__Event', 'name': 'Sea, You Again', 'id': 'seayouagain' },
  { 'group': '__Event', 'name': 'OuteR: Automata', 'id': 'outerautomata' },
  { 'group': '__Event', 'name': 'School Of Lock', 'id': 'schooloflock' },
  { 'group': '__Event', 'name': 'Dazzling Cupid: Tia', 'id': 'dazzlingcupid_tia' },
  { 'group': '__Event', 'name': 'Dazzling Cupid: Naga', 'id': 'dazzlingcupid_naga' },
  { 'group': '__Event', 'name': 'A.C.P.U.! FREEZE!', 'id': 'acpufreeze' },
  { 'group': '__Event', 'name': 'RED ASH 1', 'id': 'redash1' },
  { 'group': '__Event', 'name': 'RED ASH 2', 'id': 'redash2' },
  { 'group': '__Event', 'name': 'Alone Survivor', 'id': 'alonesurvivor' },
  { 'group': '__Event', 'name': 'Neverland', 'id': 'neverland' },
  { 'group': '__Event', 'name': 'New Year New Sword', 'id': 'newyearnewsword' },
  { 'group': '__Event', 'name': 'Lion Heart', 'id': 'lionheart' },
  { 'group': '__Event', 'name': 'Dirty Backyard', 'id': 'dirtybackyard' },
  { 'group': '__Event', 'name': 'Perfect Maid', 'id': 'perfectmaid' },
  { 'group': '__Event', 'name': 'BOOM\'s DAY', 'id': 'boomsday' },
  { 'group': '__Event', 'name': 'Kill The Lord', 'id': 'killthelord' },
  { 'group': '__Event', 'name': 'Re:Cipe For You', 'id': 'recipeforyou' },
  { 'group': '__Event', 'name': 'Pirate Cafe', 'id': 'piratecafe' },
  { 'group': '__Event', 'name': 'One More Time', 'id': 'onemoretime' },
  { 'group': '__Event', 'name': 'Last Kingdom', 'id': 'lastkingdom' },
  { 'group': '__Event', 'name': 'D.ARK HERO', 'id': 'darkhero' },
  { 'group': '__Event', 'name': 'Golden Coin Rush', 'id': 'goldencoinrush' },
  { 'group': '__Event', 'name': 'Claymore!', 'id': 'claymore' },
  { 'group': '__Event', 'name': 'Aegis the Diver', 'id': 'aegisthediver' },
  { 'group': '__Event', 'name': 'Beauty Full Shot', 'id': 'beautyfullshot' },
  { 'group': '__Event', 'name': 'Juvenile Days', 'id': 'juveniledays' },
  { 'group': '__Event', 'name': 'Color Less', 'id': 'colorless' },
  { 'group': '__Event', 'name': 'Jinx Player', 'id': 'jinxplayer' },
  { 'group': '__Event', 'name': 'Phantom Thief Detective', 'id': 'phantomthief' },
  { 'group': '__Event', 'name': 'Life Again', 'id': 'lifeagain' },
  { 'group': '__Event', 'name': 'Old Tales', 'id': 'oldtales' },
  { 'group': '__Event', 'name': 'Secret Garden', 'id': 'secretgarden' },
  { 'group': '__Event', 'name': 'Ice Dragon Saga', 'id': 'icedragonsaga' },
  { 'group': '__Event', 'name': 'Footstep, Walk, Run', 'id': 'footstepwalkrun' },
  { 'group': '__Event', 'name': 'Wisdom Spring', 'id': 'wisdomspring' },
  { 'group': '__Event', 'name': 'Romantic Valentine', 'id': 'romanticvalentine' },
  { 'group': '__Event', 'name': 'Evangelion', 'id': 'evangelion' },
  { 'group': '__Event', 'name': 'For Rest', 'id': 'forrest' },
  { 'group': '__Event', 'name': 'New Flavor', 'id': 'newflavor' },
  { 'group': '__Event', 'name': 'True Flavor', 'id': 'trueflavor' },
  { 'group': '__Event', 'name': 'Unbreakable Sphere', 'id': 'unbreakablesphere' },
  { 'group': '__Event', 'name': 'Arcana Archive', 'id': 'arcanearchive' },
  { 'group': '__Event', 'name': 'Lord, for Justice', 'id': 'lordforjustice' },
  { 'group': '__Event', 'name': 'Memories Teller 1', 'id': 'memoriesteller_1' },
  { 'group': '__Event', 'name': 'Memories Teller 2', 'id': 'memoriesteller_2' },
  { 'group': '__Event', 'name': 'Over the Horizon', 'id': 'overthehorizon' },
  { 'group': '__Event', 'name': 'Boom the Ghost!', 'id': 'boomtheghost' },
  { 'group': '__Event', 'name': 'Evangelion: Second Quest 1', 'id': 'secondquest1' },
  { 'group': '__Event', 'name': 'Evangelion: Second Quest 2', 'id': 'secondquest2' },
  { 'group': '__Event', 'name': 'Absolute', 'id': 'absolute' },
  { 'group': '__Event', 'name': 'Coins In Rush', 'id': 'coinsinrush' },
  { 'group': '__Event', 'name': 'Reborn Evil', 'id': 'rebornevil' },
  { 'group': '__Event', 'name': 'Go! Ninja Thief', 'id': 'goninjathief' },
  { 'group': '__Event', 'name': 'Blank Ticket', 'id': 'blankticket' },
  { 'group': '__Event', 'name': 'Terminus Ticket', 'id': 'terminusticket' },
  { 'group': '__Event', 'name': 'Terminus Ticket AZX: Soline', 'id': 'azxservicetime_3' },
  { 'group': '__Event', 'name': 'Terminus Ticket AZX: Diesel', 'id': 'azxservicetime_6' },
  { 'group': '__Event', 'name': 'Terminus Ticket AZX: Brid', 'id': 'azxservicetime_9' },
  { 'group': '__Event', 'name': 'Ark Guardian', 'id': 'arkguardian' },
  { 'group': '__Event', 'name': 'Sin Editor', 'id': 'sineditor' },
  { 'group': '__Event', 'name': 'Fatal Maid', 'id': 'fatalmaid' },
  { 'group': '__Event', 'name': 'Lie Cause Recoil', 'id': 'liecauserecoil' },
  { 'group': '__Event', 'name': 'Enter Heaven', 'id': 'enterheaven' },
  { 'group': '__Event', 'name': '2x2 Love 1', 'id': 'twoxtwo1' },
  { 'group': '__Event', 'name': '2x2 Love 2', 'id': 'twoxtwo2' },
  { 'group': '__Event', 'name': 'Good World', 'id': 'goodworld' },
  { 'group': '__Event', 'name': 'Star Anis', 'id': 'staranis' },
  { 'group': '__Event', 'name': 'B-side Idol', 'id': 'bsideidol' },

  { 'group': '__Story', 'name': 'Story 00-01', 'id': 'story0001' },
  { 'group': '__Story', 'name': 'Story 00-01 no filter', 'id': 'story0001_2' },
  { 'group': '__Story', 'name': 'Story 00-02', 'id': 'story0002' },
  { 'group': '__Story', 'name': 'Story 00-02 no filter', 'id': 'story0002_2' },
  { 'group': '__Story', 'name': 'Story 00-03', 'id': 'story0003' },
  { 'group': '__Story', 'name': 'Story 02-01', 'id': 'story0201' },
  { 'group': '__Story', 'name': 'Story 04-01', 'id': 'story0401' },
  { 'group': '__Story', 'name': 'Story 04-02', 'id': 'story0401_2' },
  { 'group': '__Story', 'name': 'Story 04-02 (CN)', 'id': 'story0401_3' },
  { 'group': '__Story', 'name': 'Story 04-05', 'id': 'story0405' },
  { 'group': '__Story', 'name': 'Story 07-02', 'id': 'story0702' },
  { 'group': '__Story', 'name': 'Story 12-01', 'id': 'story1201' },
  { 'group': '__Story', 'name': 'Story 13-02', 'id': 'story1302' },
  { 'group': '__Story', 'name': 'Story 13-03', 'id': 'story1303' },
  { 'group': '__Story', 'name': 'Story 14-01', 'id': 'story1401' },
  { 'group': '__Story', 'name': 'Story 14-03', 'id': 'story1403' },
  { 'group': '__Story', 'name': 'Story 14-05', 'id': 'story1405' },
  { 'group': '__Story', 'name': 'Story 15-01', 'id': 'story1501' },
  { 'group': '__Story', 'name': 'Story 19-01', 'id': 'story1902' },
  { 'group': '__Story', 'name': 'Story 20-01', 'id': 'story2002' },
  { 'group': '__Story', 'name': 'Story 21-01', 'id': 'story2101' },
  { 'group': '__Story', 'name': 'Story 22-01', 'id': 'story2201' },
  { 'group': '__Story', 'name': 'Story 22-02', 'id': 'story2202' },
  { 'group': '__Story', 'name': 'Story 22-06', 'id': 'story2206' },
  { 'group': '__Story', 'name': 'Story 25-01', 'id': 'story2501' },
  { 'group': '__Story', 'name': 'Story 26-02', 'id': 'story2602' },

  { 'group': '__z', 'name': 'Boss: Mother Whale', 'id': 'bba001' },
  { 'group': '__z', 'name': 'Boss: Harvester', 'id': 'bbg001' },
  { 'group': '__z', 'name': 'Boss: Chatterbox', 'id': 'bbg002' },
  { 'group': '__z', 'name': 'Boss: Blacksmith', 'id': 'bbg003' },
  { 'group': '__z', 'name': 'Predator', 'id': 'c9005' },
  { 'group': '__z', 'name': 'Predator: leader', 'id': 'c9005_01' },
  { 'group': '__z', 'name': 'Boss: Storm Bringer', 'id': 'eba001' },
  { 'group': '__z', 'name': 'Boss: Gatekeeper Blue', 'id': 'eba003' },
  { 'group': '__z', 'name': 'Boss: Gatekeeper Green', 'id': 'eba003_green' },
  { 'group': '__z', 'name': 'Boss: Gatekeeper Red', 'id': 'eba003_hsta' },
  { 'group': '__z', 'name': 'Boss: Land Eater', 'id': 'ebg001' },
  { 'group': '__z', 'name': 'Boss: Material H', 'id': 'ebg002' },
  { 'group': '__z', 'name': 'Boss: Nihilister', 'id': 'mba002' },
  { 'group': '__z', 'name': 'Boss: Alteisen', 'id': 'mbg001' },
  { 'group': '__z', 'name': 'Boss: Grave Digger', 'id': 'mbg002' },
  { 'group': '__z', 'name': 'Boss: Modernia', 'id': 'mbg004' },
  { 'group': '__z', 'name': 'Boss: Modernia Intro', 'id': 'mbg004_appearance' }

]

const customZoomSettings = {
  'oldtales': { zoom: 0.52, offsetX: 0, offsetY: 0 },
  'staranis': { zoom: 0.35, offsetX: 100, offsetY: 0 },
  'favorite_c112': { zoom: 0.28, offsetX: 60, offsetY: 0 },
  'favorite_c030': { zoom: 0.24, offsetX: 60, offsetY: 0 },
  'favorite_c032': { zoom: 0.3, offsetX: 60, offsetY: 0 },
}

const voiceGroupMap = {
  'c271_01': 'c271',
  'c271_02': 'c271',
  'c032_01': 'c032',
  'c030_01': 'c030',
  'c030_02': 'c030',
  'c090_02': 'c090',
  'c091_01': 'c091',
  'c093_01': 'c093',
  'c095_01': 'c095',
}

const setCustomZoom = (characterId, canvas, transformScale) => {
  if (customZoomSettings[characterId]) {
    const settings = customZoomSettings[characterId]
    transformScale = settings.zoom
    
    if (canvas) {
      canvas.style.transform = 'scale(' + transformScale + ')'
      
      if (settings.offsetX !== undefined) {
        const currentLeft = parseInt(canvas.style.left.replaceAll('px', '')) || 0
        canvas.style.left = (currentLeft + settings.offsetX) + 'px'
      }
      
      if (settings.offsetY !== undefined) {
        const currentTop = parseInt(canvas.style.top.replaceAll('px', '')) || 0
        canvas.style.top = (currentTop + settings.offsetY) + 'px'
      }
    }
    
    return transformScale
  }
  
  return transformScale
}

const voiceModules = import.meta.glob('@/assets/voice/**/*.mp3', { eager: true })

const voiceMap = {}
Object.entries(voiceModules).forEach(([path, module]) => {
  const match = path.match(/\/([a-z0-9_]+)\/([a-z0-9_]+)\.mp3$/)
  if (match) {
    const folderName = match[1]
    const filename = match[2]
    
    const numberMatch = filename.match(/_(\d+)$/)
    if (!numberMatch) return
    
    const voiceNumber = parseInt(numberMatch[1])
    
    let pose = 'normal'
    if (voiceNumber >= 7) {
      pose = 'cover'
    }
    
    if (!voiceMap[folderName]) {
      voiceMap[folderName] = {}
    }
    if (!voiceMap[folderName][pose]) {
      voiceMap[folderName][pose] = []
    }
    
    voiceMap[folderName][pose].push(module.default)
  }
})

Object.keys(voiceMap).forEach((characterId) => {
  Object.keys(voiceMap[characterId]).forEach((pose) => {
    voiceMap[characterId][pose].sort()
  })
})

l2dData.forEach((character) => {
  if (voiceMap[character.id]) {
    character.voices = voiceMap[character.id]
  }
})

export { voiceMap, voiceGroupMap, setCustomZoom, customZoomSettings }
export default l2dData